//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 09:26:52 PM IST 
//


package friends.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the friends.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Friends_QNAME = new QName("http://xml.friends", "friends");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: friends.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Friends }
     * 
     */
    public Friends createFriends() {
        return new Friends();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Friends }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.friends", name = "friends")
    public JAXBElement<Friends> createFriends(Friends value) {
        return new JAXBElement<Friends>(_Friends_QNAME, Friends.class, null, value);
    }

}
